#define SSID_NERDLAB "FILL SSID NERDLAB"
#define PASSWORD_NERDLAB "FILL PASSWORD NERDLAB"

#define SSID_PRIVATE "FILL SSID PRIVATE"
#define PASSWORD_PRIVATE "FILL PASSWORD PRIVATE"
#define MQTT_SERVER "FILL MQTT SERVER TEST"
